version: '3'
services:
    # node-app:
    #     build:
    #         context: .
    #         dockerfile: node.simple.Dockerfile
    #     ports:
    #         # 映射到外部端口:应用端口
    #         - 3002:3000
    nginx-app:
        build:
            context: .
            dockerfile: nginx.simple.Dockerfile
        ports:
            - 4000:80
